const LEVEL_WIDTH = window.innerWidth;
const LEVEL_HEIGHT = window.innerHeight;

let SHOW_DEBUG = true;
let SHOW_QUADTREE = false;
let USE_QUADTREE = true;
let SHOW_FLOCK_COLORS = true;

let COHESION_MULTIPLIER = 0.004;
let SEPARATION_MULTIPLIER = 0.05;
let ALIGNMENT_MULTIPLIER = 0.05;

let FLOCKS = 5;
let BOID_AMOUNT = 2000;
let BOID_MAX_SPEED = 2;
let BOID_SIZE = 3;
let BOID_PERSONAL_SPACE = 5;
let BOID_VISION = 48;
let BOID_BOUNCE_AT_EDGES = true;

let MAX_ENTITIES_PER_QUADTREE = 32;
let MIN_QUADTREE_SIZE = 20;

const LEVEL_SPACING_LEFT = 256;
const TURN_AROUND_AREA = 8;

const SLIDER_WIDTH = 192;
const UI_SPACING = 48;